nodeLinker: "pnp"
yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  "eslint-plugin-flowtype@*":
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true
  "react-slick@^0.29.0":
    dependencies:
      "react": "18.2.0"
  "slick-carousel@^1.8.1":
    dependencies:
      "react": "18.2.0"
  "recoil-persist@^5.1.0":
    dependencies:
      "recoil": "latest"
